### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by Nonbiuld** [LiuZhu-CV/PAIF#1]
In the robust_test.py
parser.add_argument("--config",
                    default='configs/voc.yaml',
                    type=str,
                    help="config")
There is no file "voc.yaml" in your codes, please provide voc.yaml . Thanks!

**Comment by LiuZhu-CV** [comment]
Uploaded at "https://drive.google.com/drive/folders/10Wd8AKJzg6Cgvem_xY8uYavReuKWiEpO"  I will upate the whole codes soon.
